### ISSUE TITLE
Defaults pragma/implDefaults incorrectly creates `new<MYTYPE>()` proc for object-type

### ISSUE THREAD

**Issue by PhilippMDoerner** [beef331/constructor#4]
Heyho, I am using constructor together with orm for convenience purposes and stumbled over this bug:

```nim
import norm/[model, pragmas]
import constructor/defaults
import std/times

type 
Item* {.defaults, tableName: "atable".} = ref object of Model
  name*: string = ""
  campaign_id*: int64 = -2
  update_datetime*: DateTime = now()
  creation_datetime*: DateTime = now()
  
implDefaults(Item)

let i1 = newItem() # Works but should it?
#let i2 = initItem() # does not compile
```
According to what we discussed on discord, the object as a value-allocated type `Item` should create a `initItem()` in accordance with nim best practices.
Instead it gets a `newItem()` proc like a heap allocated object.

This appears to be an issue due to inheritance in the type.

**Comment by beef331** [comment]
`ref object` is not value allocated, this is a reference object so should use `new`.
