### ISSUE TITLE
For #6 : Add runnable examples and doc comments to macros

### ISSUE THREAD

**Issue by PhilippMDoerner** [beef331/constructor#6]
We had discussed this one on discord a couple days back. Having runable examples for the macros and doc comments could be useful.

I'll make a PR to add some that you can do with as you please, just wanted to contribute something mildly useful.

**Comment by PhilippMDoerner** [comment]
I appear to be unable to get this runnable example to work:
```nim
    import std/options

    type
      A* = object
        myInt*: int
        myOption*: Option[int] 
        myStr*: string

    proc init(T: typedesc[A], myInt: int, myOption: Option[int], myStr: string): A {.constr.}
    assert A.init(5, some(2), "hello") == A(myInt: 5, myOption: some(2), myStr: "hello")
```

This doesn't lead to a propper "init" proc being created. I'm not quite sure what I'm doing wrong there though

**Comment by beef331** [comment]
Worked fine for me
