### ISSUE TITLE
example code fails when flag --experimental:strictFuncs is set

### ISSUE THREAD

**Issue by Luteva-ssh** [beef331/constructor#9]
when trying the example code:
```nim
import constructor/defaults
type Thingy{.defaults.} = object
  a: float = 10 # Can do it this way
  b = "Hmm" # Can also do it this way
  c = 10
implDefaults(Thingy) # Required to embed the procedure
assert initThingy() == Thingy(a: 10, b: "Hmm", c: 10)
```
with the flag --experimental:strictFuncs set, the compiler complains:
..../.nimble/pkgs/micros-0.1.5/micros/definitions/routines.nim(109, 49) template/generic instantiation of & from here
..../nim-1.6.6/lib/system.nim(1675, 8) Error: '&' can have side effects an object reachable from 'x' is potentially mutated
..../nim-1.6.6/lib/system.nim(1689, 23) the mutation is here
..../nim-1.6.6/lib/system.nim(1689, 23) is the statement that connected the mutation to the parameter

It would be nice to be able to use the lib independently of that flag.

**Comment by beef331** [comment]
Sorry did not see this issue until now, was resolved in micros some time ago.
